### ISSUE TITLE
Always initialize cachefs stream wrapper

### ISSUE THREAD

**Issue by atrauzzi** [shpasser/GaeSupportL5#20]
Given that the local development environment simulates memcache and has a nice interface, what would you say to moving this fine fella outside of the check?

https://github.com/shpasser/GaeSupportL5/blob/master/src/Shpasser/GaeSupportL5/Foundation/Application.php#L57

**Comment by shpasser** [comment]
Actually not all the developers use `laravel/homestead` as their local environment. Some use MAMP, some use WAMP(still have some pending issues to be committed) and some use `dev_appserver.py`. Since not all of the environments have `memcache` up and running I would prefer to leave the choice with the developer. Anyway it is a good idea to add some lines to the `readme` file about possible use of `cachefs` in local environments.

**Comment by atrauzzi** [comment]
Ah, alright.  Perhaps another env var then?

**Comment by shpasser** [comment]
Sure.

**Comment by atrauzzi** [comment]
@shpasser - It's fairly basic, but if you want you can take a look at the MR now.  Let me know if you'd prefer things be checked differently anywhere.

**Comment by shpasser** [comment]
On second thought, the main purpose of `caches` was to replace GCS in order to reduce average request latency, then why would we need it in local development environment?

**Comment by atrauzzi** [comment]
To simulate the behaviour locally.

**Comment by shpasser** [comment]
Ok, I see. Will have to think it over. Thanks for the pull request.

**Comment by shpasser** [comment]
Very close to finish working on this issue, still have to do some tests. Will keep you posted.

**Comment by atrauzzi** [comment]
Exciting!   I'll continue to wait :)

**Comment by shpasser** [comment]
Almost finished. Need to make the unit tests green.

**Comment by shpasser** [comment]
Just pushed it to the master branch.

**Comment by shpasser** [comment]
It is time to close this one.

**Comment by atrauzzi** [comment]
Sorry, I've been using the latest dev changes and haven't encountered any issues.  So I'd say it all checks out! :)
