### ISSUE TITLE
 Laravel does not create the laravel_session

### ISSUE THREAD

**Issue by mgallegos** [shpasser/GaeSupportL5#34]
I don't know why Laravel is not creating the laravel_session cookie, I'm experimenting this problem on the development server and on GAE. 

The only clue I have is this error I'm getting on the development server:

Unable to delete function dlUnable to delete function mb_send_mailERROR:root:php failure (255) with:
stdout:
X-Powered-By: PHP/5.5.23
Content-type: text/html

Any ideas? (Great work on your package by the way)

**Comment by shpasser** [comment]
In order to help I will need your configuration files: `.env`, `php.ini`, `app.yaml` and also cached configuration file `bootstrap/cache/config.php`. A log file could help too.

**Comment by mgallegos** [comment]
> In order to help I will need your configuration files: .env, php.ini, app.yaml 

You can find them here:

https://github.com/mgallegos/decima-erp

See .env.gae.production for gae configuration.

> and also cached configuration file bootstrap/cache/config.php. A log file could help too.

I'm using L 5.0 so I do not have that file.

**Comment by mgallegos** [comment]
You can take a look to the live application in the following link:

http://elegant-poetry-104823.appspot.com/

**Comment by shpasser** [comment]
I do not see any problems with your configuration assuming a real `APP_KEY` is used. Still the information about the error is not sufficient, please send me the related stack trace and log entries. BTW, I've managed to find a report on similar issue that might be of interest for you:

https://code.google.com/p/googleappengine/issues/detail?id=12127

Anyway in order to do more digging I will need more information on the error, the best thing would be if you could prepare some demo app demonstrating the issue, so I could play with and try to understand the problem.

**Comment by mgallegos** [comment]
Thanks for you help, I managed to solve it.

The problem was caused by the empty lines at the beginning of this script:

https://github.com/mgallegos/decima-erp-bk/blob/master/workbench/mgallegos/decima-accounting/src/routes.php

**Comment by shpasser** [comment]
Very good then, I'm going to close this one.
